# Generated by Django 2.2.3 on 2020-04-01 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Desarroladores',
            new_name='Desarrolladores',
        ),
    ]
