# Generated by Django 2.2.3 on 2020-04-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0002_auto_20200401_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrolladore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tfno', models.CharField(max_length=15, verbose_name='Telefono')),
                ('seniority', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=15)),
                ('lenguajes', models.CharField(max_length=255)),
                ('estudios_Universitaros', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('disponible', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Desarrolladores',
        ),
    ]
