# Generated by Django 2.2.3 on 2020-04-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0003_auto_20200401_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desarrolladore',
            name='estudios_Universitaros',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
