# Generated by Django 2.2.3 on 2020-04-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0004_auto_20200406_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='desarrolladore',
            name='ingles',
            field=models.CharField(default='basico', max_length=20),
        ),
    ]
